apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-endtoend-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: dockerdebu4321/endtoend
        ports:
        - containerPort: 8085